import { ICartType } from "@/types/cart.interface";
import { IDiamond } from "@/types/diamond.interface";

export const diamondData: IDiamond[] = [
  {
    productType: ICartType.Diamond,
    diamondId: "D001",
    image:
      "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/Products%2FDiamond%2Fdiamond.png?alt=media&token=0a3f7a6f-6f7d-45b3-99b9-f4717fb440f6",
    shape: "Pear",
    weight: "1.5",
    colorLevel: "F",
    clarity: "VVS2",
    certification: "GIA",
    size: "10.5*6.47",
    fluorescence: "None",
    qualityOfCut: "Excellent",
    price: 535790600,
  },
  {
    productType: ICartType.Diamond,
    diamondId: "D002",
    image:
      "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/Products%2FDiamond%2Fdiamond.png?alt=media&token=0a3f7a6f-6f7d-45b3-99b9-f4717fb440f6",
    shape: "Round",
    weight: "0.34",
    colorLevel: "D",
    clarity: "VS2",
    certification: "GIA",
    size: "4.4",
    fluorescence: "Medium",
    qualityOfCut: "Excellent",
    price: 21924560,
  },
  {
    productType: ICartType.Diamond,
    diamondId: "D003",
    image:
      "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/Products%2FDiamond%2Fdiamond.png?alt=media&token=0a3f7a6f-6f7d-45b3-99b9-f4717fb440f6",
    shape: "Round",
    weight: "0.34",
    colorLevel: "D",
    clarity: "VS2",
    certification: "GIA",
    size: "4.4",
    fluorescence: "Medium",
    qualityOfCut: "Excellent",
    price: 21924560,
  },
  {
    productType: ICartType.Diamond,
    diamondId: "D004",
    image:
      "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/Products%2FDiamond%2Fdiamond.png?alt=media&token=0a3f7a6f-6f7d-45b3-99b9-f4717fb440f6",
    shape: "Round",
    weight: "0.35",
    colorLevel: "D",
    clarity: "VS3",
    certification: "GIA",
    size: "4.4",
    fluorescence: "Medium",
    qualityOfCut: "Excellent",
    price: 21924560,
  },
  {
    productType: ICartType.Diamond,
    diamondId: "D005",
    image:
      "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/Products%2FDiamond%2Fdiamond.png?alt=media&token=0a3f7a6f-6f7d-45b3-99b9-f4717fb440f6",
    shape: "Round",
    weight: "0.35",
    colorLevel: "D",
    clarity: "IF",
    certification: "GIA",
    size: "4.5",
    fluorescence: "Faint",
    qualityOfCut: "Excellent",
    price: 34422800,
  },
  {
    productType: ICartType.Diamond,
    diamondId: "D006",
    image:
      "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/Products%2FDiamond%2Fdiamond.png?alt=media&token=0a3f7a6f-6f7d-45b3-99b9-f4717fb440f6",
    shape: "Round",
    weight: "0.33",
    colorLevel: "D",
    clarity: "IF",
    certification: "GIA",
    size: "4.5",
    fluorescence: "Medium",
    qualityOfCut: "Excellent",
    price: 34422800,
  },
  {
    productType: ICartType.Diamond,
    diamondId: "D007",
    image:
      "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/Products%2FDiamond%2Fdiamond.png?alt=media&token=0a3f7a6f-6f7d-45b3-99b9-f4717fb440f6",
    shape: "Round",
    weight: "0.46",
    colorLevel: "D",
    clarity: "VVS2",
    certification: "GIA",
    size: "5.0",
    fluorescence: "None",
    qualityOfCut: "Excellent",
    price: 66165660,
  },
  {
    productType: ICartType.Diamond,
    diamondId: "D008",
    image:
      "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/Products%2FDiamond%2Fdiamond.png?alt=media&token=0a3f7a6f-6f7d-45b3-99b9-f4717fb440f6",
    shape: "Round",
    weight: "0.5",
    colorLevel: "D",
    clarity: "VSS2",
    certification: "GIA",
    size: "5.0",
    fluorescence: "Medium",
    qualityOfCut: "Excellent",
    price: 64841200,
  },
  {
    productType: ICartType.Diamond,
    diamondId: "D009",
    image:
      "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/Products%2FDiamond%2Fdiamond.png?alt=media&token=0a3f7a6f-6f7d-45b3-99b9-f4717fb440f6",
    shape: "Round",
    weight: "0.5",
    colorLevel: "D",
    clarity: "VSS2",
    certification: "GIA",
    size: "5.0",
    fluorescence: "Medium",
    qualityOfCut: "Excellent",
    price: 64841200,
  },
  {
    productType: ICartType.Diamond,
    diamondId: "D010",
    image:
      "https://firebasestorage.googleapis.com/v0/b/diamoondb-1412.appspot.com/o/Products%2FDiamond%2Fdiamond.png?alt=media&token=0a3f7a6f-6f7d-45b3-99b9-f4717fb440f6",
    shape: "Round",
    weight: "0.5",
    colorLevel: "D",
    clarity: "VSS2",
    certification: "GIA",
    size: "5.0",
    fluorescence: "Medium",
    qualityOfCut: "Excellent",
    price: 64841200,
  },
];
