import { ICartType } from "@/types/cart.interface";
import { IDiamond } from "@/types/diamond.interface";

export const diamondData: IDiamond[] = [
  {
    productType: ICartType.Diamond,
    diamondId: "D001",
    image: "https://jemmia.vn/wp-content/uploads/2023/09/image-3-1.png",
    shape: "Pear",
    weight: "1.5",
    color: "F",
    clarity: "VVS2",
    certification: "GIA",
    size: "10.5*6.47",
    fluorescence: "None",
    qualityOfCut: "Excellent",
    price: 535790600,
  },
  {
    productType: ICartType.Diamond,
    diamondId: "D002",
    image: "https://jemmia.vn/wp-content/uploads/2023/09/image-3-1.png",
    shape: "Round",
    weight: "0.34",
    color: "D",
    clarity: "VS2",
    certification: "GIA",
    size: "4.4",
    fluorescence: "Medium",
    qualityOfCut: "Excellent",
    price: 21924560,
  },
  {
    productType: ICartType.Diamond,
    diamondId: "D003",
    image: "https://jemmia.vn/wp-content/uploads/2023/09/image-3-1.png",
    shape: "Round",
    weight: "0.34",
    color: "D",
    clarity: "VS2",
    certification: "GIA",
    size: "4.4",
    fluorescence: "Medium",
    qualityOfCut: "Excellent",
    price: 21924560,
  },
  {
    productType: ICartType.Diamond,
    diamondId: "D004",
    image: "https://jemmia.vn/wp-content/uploads/2023/09/image-3-1.png",
    shape: "Round",
    weight: "0.35",
    color: "D",
    clarity: "VS3",
    certification: "GIA",
    size: "4.4",
    fluorescence: "Medium",
    qualityOfCut: "Excellent",
    price: 21924560,
  },
  {
    productType: ICartType.Diamond,
    diamondId: "D005",
    image: "https://jemmia.vn/wp-content/uploads/2023/09/image-3-1.png",
    shape: "Round",
    weight: "0.35",
    color: "D",
    clarity: "IF",
    certification: "GIA",
    size: "4.5",
    fluorescence: "Faint",
    qualityOfCut: "Excellent",
    price: 34422800,
  },
];
