import { ICartType } from "@/types/cart.interface";
import { IJewelry, IJewelryStatus } from "@/types/jewelry.interface";

export const jewelryData: IJewelry[] = [
  {
    productType: ICartType.Jewelry,
    jewelryId: "J001",
    jewelryCategory: "Earrings",
    jewelryName: "18K DIAMOND EARRINGS",
    image: "https://jemmia.vn/wp-content/uploads/2024/04/1-copy-9.jpg",
    image2: "https://jemmia.vn/wp-content/uploads/2024/04/2-copy-9.jpg",
    mainStoneSize: "Round 4ly",
    sideStoneType: "Diamond",
    sideStoneQuantity: 48,
    sideStoneWeight: 0.66,
    goldType: "White gold",
    goldKarat: "18K",
    goldWeight: "0.95",
    price: 36514800,
    status: IJewelryStatus.Available,
  },
  {
    productType: ICartType.Jewelry,
    jewelryId: "J002",
    jewelryCategory: "Earrings",
    jewelryName: "18K DIAMOND EARRINGS",
    image: "https://jemmia.vn/wp-content/uploads/2024/04/1-copy-8.jpg",
    image2: "https://jemmia.vn/wp-content/uploads/2024/04/3-copy-13.jpg",
    mainStoneSize: "Round 5ly",
    sideStoneType: "Diamond",
    sideStoneQuantity: 36,
    sideStoneWeight: 0.18,
    goldType: "White gold",
    goldKarat: "18K",
    goldWeight: "0.86",
    price: 20210400,
    status: IJewelryStatus.Available,
  },
  {
    productType: ICartType.Jewelry,
    jewelryId: "J003",
    jewelryCategory: "Pendant",
    jewelryName: "18K DIAMOND PENDANT",
    image: "https://jemmia.vn/wp-content/uploads/2024/04/2-copy-7.jpg",
    image2: "https://jemmia.vn/wp-content/uploads/2024/04/1-copy-7.jpg",
    mainStoneSize: "Round 5ly",
    sideStoneType: "Diamond",
    sideStoneQuantity: 24,
    sideStoneWeight: 1.05,
    goldType: "White gold",
    goldKarat: "18K",
    goldWeight: "0.53",
    price: 29349600,
    status: IJewelryStatus.Available,
  },
  {
    productType: ICartType.Jewelry,
    jewelryId: "J004",
    jewelryCategory: "Pendant",
    jewelryName: "18K DIAMOND PENDANT",
    image: "https://jemmia.vn/wp-content/uploads/2024/04/1_cam_01-copy-4.jpg",
    image2: "https://jemmia.vn/wp-content/uploads/2024/04/4-copy-4-768x768.jpg",
    mainStoneSize: "Round 5ly",
    sideStoneType: "Diamond",
    sideStoneQuantity: 21,
    sideStoneWeight: 0.24,
    goldType: "White gold",
    goldKarat: "18K",
    goldWeight: "0.5",
    price: 17043600,
    status: IJewelryStatus.Available,
  },
  {
    productType: ICartType.Jewelry,
    jewelryId: "J005",
    jewelryCategory: "Pendant",
    jewelryName: "18K DIAMOND PENDANT",
    image: "https://jemmia.vn/wp-content/uploads/2024/04/1_cam_01-copy-3.jpg",
    image2: "https://jemmia.vn/wp-content/uploads/2024/04/1_cam_02-copy-3.jpg",
    mainStoneSize: "Round 5ly",
    sideStoneType: "Diamond",
    sideStoneQuantity: 39,
    sideStoneWeight: 0.5625,
    goldType: "White gold",
    goldKarat: "18K",
    goldWeight: "1.11",
    price: 27524280,
    status: IJewelryStatus.Available,
  },
  {
    productType: ICartType.Jewelry,
    jewelryId: "J006",
    jewelryCategory: "Pendant",
    jewelryName: "18K DIAMOND PENDANT",
    image: "https://jemmia.vn/wp-content/uploads/2024/04/2-copy-6.jpg",
    image2: "https://jemmia.vn/wp-content/uploads/2024/04/3-copy-9.jpg",
    mainStoneSize: "Round 5ly",
    sideStoneType: "Diamond",
    sideStoneQuantity: 48,
    sideStoneWeight: 0.5252,
    goldType: "White gold",
    goldKarat: "18K",
    goldWeight: "0.37",
    price: 30634800,
    status: IJewelryStatus.Available,
  },
  {
    productType: ICartType.Jewelry,
    jewelryId: "J007",
    jewelryCategory: "Ring",
    jewelryName: "18K DIAMOND RING",
    image:
      "https://jemmia.vn/wp-content/uploads/2024/02/nhan-kim-cuong-nu-18k-VNF2022102914-2.jpg",
    image2:
      "https://jemmia.vn/wp-content/uploads/2024/02/nhan-kim-cuong-nu-18k-VNF2022102914-4.jpg",
    mainStoneSize: "Round 5ly",
    sideStoneType: "Diamond",
    sideStoneQuantity: 48,
    sideStoneWeight: 0.5252,
    goldType: "White gold",
    goldKarat: "18K",
    goldWeight: "0.37",
    price: 30634800,
    status: IJewelryStatus.Available,
  },
  {
    productType: ICartType.Jewelry,
    jewelryId: "J008",
    jewelryCategory: "Ring",
    jewelryName: "18K DIAMOND RING",
    image:
      "https://jemmia.vn/wp-content/uploads/2024/02/nhan-kim-cuong-nu-18k-VNF2022112958-3.jpg",
    image2:
      "https://jemmia.vn/wp-content/uploads/2024/02/nhan-kim-cuong-nu-18k-VNF2022112958-4.jpg",
    mainStoneSize: "Round 5ly",
    sideStoneType: "Diamond",
    sideStoneQuantity: 48,
    sideStoneWeight: 0.5252,
    goldType: "White gold",
    goldKarat: "18K",
    goldWeight: "0.37",
    price: 30634800,
    status: IJewelryStatus.Available,
  },
  {
    productType: ICartType.Jewelry,
    jewelryId: "J009",
    jewelryCategory: "Bracelet",
    jewelryName: "18K DIAMOND BRACELET",
    image:
      "https://jemmia.vn/wp-content/uploads/2023/03/vong-tay-kim-cuong-18k-lt2022082794_3.jpg",
    image2:
      "https://jemmia.vn/wp-content/uploads/2023/03/vong-tay-kim-cuong-18k-lt2022082794_1-600x600.jpg",
    mainStoneSize: "Round 5ly",
    sideStoneType: "Diamond",
    sideStoneQuantity: 48,
    sideStoneWeight: 0.5252,
    goldType: "White gold",
    goldKarat: "18K",
    goldWeight: "0.37",
    price: 30634800,
    status: IJewelryStatus.Available,
  },
  {
    productType: ICartType.Jewelry,
    jewelryId: "J010",
    jewelryCategory: "Bracelet",
    jewelryName: "18K DIAMOND BRACELET",
    image:
      "https://jemmia.vn/wp-content/uploads/2022/05/lac-tay-kim-cuong-tu-nhien-ma-lt2021062085-1.jpg",
    image2:
      "https://jemmia.vn/wp-content/uploads/2022/05/lac-tay-kim-cuong-tu-nhien-ma-lt2021062085-2.jpg",
    mainStoneSize: "Round 5ly",
    sideStoneType: "Diamond",
    sideStoneQuantity: 48,
    sideStoneWeight: 0.5252,
    goldType: "White gold",
    goldKarat: "18K",
    goldWeight: "0.37",
    price: 30634800,
    status: IJewelryStatus.Available,
  },
];
